app/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from views import *

from django.views.decorators.csrf import csrf_exempt

urlpatterns = [
    url(r'^item/price/type/$', set_price_type, name='price-type-set'),
    url(r'^items/buy/$', BuyView.as_view(), name='item-buy'),
    url(r'^items/category-(?P<slug>[-\w]+)/$', CategoryItemsView.as_view(), name='category-items'),
    url(r'^items/spec-(?P<slug>[-\w]+)/$', SpecOfferItemsView.as_view(), name='spec-items'),
    url(r'^items/(?P<slug>[-\w]+)/$', ItemDetail.as_view(), name='item-detail'),
#    url(r'^items/spec/$', ItemsView.as_view(), name='spec-items'),
    url(r'^origin-item-detail/$', TemplateView.as_view(template_name='origin/item-detail.html'), name='origin-item-detail'),
    url(r'^origin-items/$', TemplateView.as_view(template_name='origin/items.html'), name='origin-items'),
    url(r'^items/$', ItemsView.as_view(), name='items'),
    url(r'^news/$', NewsListView.as_view(), name='news'),
    url(r'^news/(?P<pk>\d+)/$', NewsDetailView.as_view(), name='news-item'),

    url(r'^$', HomeView.as_view(), name='main'),
    url(r'^about/$', AboutView.as_view(), name='about'),
    url(r'^about/team/$', AboutTeamView.as_view(), name='team'),
    url(r'^about/vacancy/$', AboutVacancyView.as_view(), name='vacancy'),
    url(r'^about/portfolio/$', AboutPortfolioView.as_view(), name='portfolio'),

    url(r'^delivery/way/$', DeliveryWayView.as_view(), name='delivery-way'),
    url(r'^delivery/calc/$', DeliveryCalcView.as_view(), name='delivery-calc'),
    url(r'^delivery/payway/$', PayWayView.as_view(), name='delivery-payway'),
    url(r'^delivery/feedback/$', FeedbackView.as_view(), name='delivery-feedback'),
    url(r'^delivery/support/$', SupportView.as_view(), name='delivery-support'),

    url(r'^search/$', SearchView.as_view(), name='search-view'),
    url(r'^login/ajax/$', LoginAjaxView.as_view(), name='login-ajax-view'),

    url(r'^order/call/$', OrderCallView.as_view(), name='order-call-view'),


    url(r'^contacts/$', ContactsView.as_view(), name='contacts'),
    url(r'^feedback/ajax/$', FeedbackAjaxView.as_view(), name='feedback-ajax'),

    url(r'^login/$', terralogin, name='auth_login'),
    url(r'^logout/$', terralogout, name='auth_logout'),

    url(r'^registration/opt/$', RegistrationOptView.as_view(), name='registration_opt'),
    # url(r'^registration/opt/ajax/$', RegistrationOptAjaxView.as_view(), name='registration_opt_ajax'),
    url(r'^registration/rent/$', RegistrationRentView.as_view(), name='registration_rent'),
    # url(r'^registration/rent/ajax/$', RegistrationRentAjaxView.as_view(), name='registration_rent_ajax'),
    # url(r'^registration/profile/$', ProfileView.as_view(), name='profile'),

    url(r'^private/profile/$', ProfileView.as_view(), name='profile'),
    url(r'^private/order/(?P<pk>\d+)/$', OrderDetailView.as_view(), name='profile_order'),

    url(r'^cart/size/$', get_cart_size, name='cart_size'),
    url(r'^cart/clear/$', csrf_exempt(clear_cart), name='clear_cart'),
    url(r'^cart/add/$', csrf_exempt(add_to_cart), name='add_to_cart'),
    url(r'^cart/item/del/(?P<product_id>\d+)/$', csrf_exempt(remove_from_cart), name='remove_from_cart'),
    url(r'^cart/$', CartView.as_view(), name='cart'),
    url(r'^promo/check/$', csrf_exempt(check_promo), name='check_promo'),
    url(r'^city/check/$', csrf_exempt(get_delivery_price), name='check_city'),

    url(r'^order/add/$', CreateOrderView.as_view(), name='order-add'),

    url(r'^subscribe/ajax/$', SubscribeAjaxView.as_view(), name='subscribe-ajax'),

    url(r'^franchise/$', FranchiseView.as_view(), name='franchise-view'),
    ]

terrafiori/urls.py
from django.conf.urls import patterns, include, url
from app.views import FeedbackView
from django.views.decorators.csrf import csrf_exempt

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
#    url(r'^$', TemplateView.as_view(template_name='index.html'), name='home'),


    url(r'^send/$', csrf_exempt(FeedbackView.as_view()), name='send'),

#    url(r'^send/$', csrf_exempt(FeedbackView.as_view()), name='send'),

    url(r'^', include('app.urls')),
    # url(r'^terrafiori/', include('terrafiori.foo.urls')),
    url(r'^robokassa/', include('robokassa.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
#    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^redactor/', include('redactor.urls')),

)

cart/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.contrib.contenttypes.models import ContentType

class Cart(models.Model):
    creation_date = models.DateTimeField(verbose_name=_('creation date'))
    checked_out = models.BooleanField(default=False, verbose_name=_('checked out'))

    class Meta:
        verbose_name = _('cart')
        verbose_name_plural = _('carts')
        ordering = ('-creation_date',)

    def __unicode__(self):
        return unicode(self.creation_date)

class ItemManager(models.Manager):
    def get(self, *args, **kwargs):
        if 'product' in kwargs:
            kwargs['content_type'] = ContentType.objects.get_for_model(type(kwargs['product']))
            kwargs['object_id'] = kwargs['product'].pk
            del(kwargs['product'])
        return super(ItemManager, self).get(*args, **kwargs)

class Item(models.Model):
    cart = models.ForeignKey(Cart, verbose_name=_('cart'))
    quantity = models.PositiveIntegerField(verbose_name=_('quantity'))
    unit_price = models.DecimalField(max_digits=18, decimal_places=2, verbose_name=_('unit price'))
    # product as generic relation
    content_type = models.ForeignKey(ContentType)
    object_id = models.PositiveIntegerField()

    objects = ItemManager()

    product_options = models.ManyToManyField("ItemOption", blank=True)

    # color = models.ForeignKey(ItemColor, blank=True)

    class Meta:
        verbose_name = _('item')
        verbose_name_plural = _('items')
        ordering = ('cart',)

    def __unicode__(self):
        return u'%d units of %s' % (self.quantity, self.product.__class__.__name__)

    @property
    def total_price(self):
        return self.quantity * self.unit_price

    # product
    def get_product(self):
        return self.content_type.get_object_for_this_type(id=self.object_id)

    def set_product(self, product):
        self.content_type = ContentType.objects.get_for_model(type(product))
        self.object_id = product.pk

    product = property(get_product, set_product)

    # options
    def get_options(self):
        return [o.option for o in self.itemoption_set.all()]

    def set_options(self, options):
        for option in options:
            itemoption = ItemOption(content_type = ContentType.objects.get_for_model(type(option)), object_id = option.pk)
            itemoption.save()
            self.product_options.add(itemoption)

    def clear_options(self):
        return self.product_options.clear()

    options = property(get_options, set_options)


class ItemOption(models.Model):
    content_type = models.ForeignKey(ContentType)
    object_id = models.PositiveIntegerField()

    # options
    def get_option(self):
        return self.content_type.get_object_for_this_type(id=self.object_id)

    option = property(get_option)

templates/private/base.html
{% extends 'base.html' %}

{% block content %}
    <div class="categories-border"></div>
    <div class="container catalog ">
    <div class="catalog-menu">
        <div class="action-title">
            <span>Личный кабинет</span>
        </div>
        <div class="spec-items">
            <ul>
                <li >
                    <a href="#" onclick="return false;">Заказы
                        <span class="hover-arrow"></span>
                    </a>
                    <ul>
                        {% for o in orders %}
                        <li {% if o.pk == order.pk %}class="active"{% endif %}>
                            <a href="{% url 'profile_order' pk=o.pk %}">Заказ №{{ o.pk }}
                                <span class="hover-arrow"></span>
                            </a>
                        </li>
                        {% endfor %}
                    </ul>
                </li>
                <li {% if active_profile == 'profile' %}class="active"{% endif %}>
                    <a href="{% url 'profile' %}">Профиль
                        <span class="hover-arrow"></span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
    <div class="catalog-items {% block catalog_bg %}{% endblock %}">
    <div class="catalog-items-top">
        <div class="basket pull-right">
            <div class="basket-icon"></div>
            <a href="{% url 'cart' %}">
                <div>Моя Корзина </div>
            </a>
            <div class="number-in-basket basket-top"> {{ cart.count|default:"Пуста" }}</div>
        </div>
        <div class="breadcrumbs">
            <ul class="">
                {% for b in breadcrumbs %}
                <li>
                    {% if forloop.last %}
                        <span>{{ b.0 }}</span>
                    {% else %}
                        <a href="{{ b.1 }}">{{ b.0 }}</a>
                    {% endif %}
                </li>
                    {% if not forloop.last %}
                        <li>
                            <span> > </span>
                        </li>
                    {% endif %}
                {% endfor %}
            </ul>
        </div>
    </div>
        {% block private_content %}{% endblock %}
    </div>

    </div>
{% endblock %}

{% block categories %}{% endblock %}

templates/private/login.html
{% extends 'base.html' %}

{% block content %}
    <div class="categories-border"></div>
    <div class="container catalog ">
        <div class="login-form-block">
            <form method="POST">
                <div class="form-group">
                    <label>
                        <input name="email" class="form-control" placeholder="Ваш e-mail" type="text" />
                    </label>
                </div>
                <div class="form-group">
                    <label>
                        <input name="password" class="form-control" placeholder="Ваш пароль" type="password" />
                    </label>
                </div>
                <div class="form-group">
                    <label>
                        <button class="btn btn-dark">Войти</button>
                    </label>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

templates/private/orders.html
{% extends 'private/base.html' %}

{% load widget_tweaks %}
{% load thumbnail %}

{% block private_content %}
    <div class="private-data-block">
        <div class="order-info">
            <div>Создан: <span>{{ order.created }}</span></div>
        </div>
        <div class="order-info">
            <div>Сумма: <span>{{ order.total_summary }}</span> руб.</div>
        </div>
        <div class="order-info">
            <div>Статус: <span>{{ order.get_status }}</span></div>
        </div>
    </div>
            <div class="cart-items">
                <table class="table">
                <thead>
                    <tr>
                        <td style="width: 175px" class="bg-dark">
                            <div class="action-title">ПРОДУКТ</div>
                        </td>
                        <td style="width: 50%">
                            <div class="action-title">ОПИСАНИЕ</div>
                        </td>
                        <td class="bg-dark">
                            <div class="action-title">
                                ЦЕНА
                            </div>
                        </td>
                        <td>
                            <div class="action-title">
                                Кол-во
                            </div>
                        </td>
                        <td class="bg-dark">
                            <div class="action-title">
                                СУММА
                            </div>
                        </td>
                    </tr>
                </thead>
                <tbody>
                    {% for item in order.cart.item_set.all %}
                    <tr class="cart-item">
                        <td class="cart-item-img bg-dark">
                            {% thumbnail item.product.images.all.0.image "100x100" crop="center" as im %}
                                <img src="{{ im.url }}">
                            {% endthumbnail %}
                        </td>
                        <td>
                            <h1>{{ item.product.name }}</h1>
                            <div class="art">Артикул: {{ item.product.art }}</div>
                            {% if item.product.desc %}
                                <div class="desc">
                                    <div class="desc-title">Описание</div>
                                    <div class="desc-text">
                                        {{ item.product.desc|linebreaksbr|truncatewords_html:"5" }}
                                    </div>
                                    <div class="cart-item-more">
                                        <a target="_blank" href="{% url 'item-detail' slug=item.product.slug %}">Подробнее...</a>
                                    </div>
                                </div>
                            {% endif %}
                        </td>
                        <td class="bg-dark cart-money">
                            {{ item.unit_price }} руб.
                        </td>
                        <td>
                            <div class="cart-count number-in-basket">{{ item.quantity }}</div>
                        </td>
                        <td class="bg-dark cart-money">
                            <div class="cart-summ">{{ item.total_price }} руб.</div>
                        </td>
                    </tr>
                    {% endfor %}

                </tbody>
                </table>
            </div>
{% endblock %}

templates/private/profile.html
{% extends 'private/base.html' %}

{% load widget_tweaks %}

{% block private_content %}
    <div class="private-data-block">
        <form method="POST" class="private-controls">
            {% csrf_token %}
            <div class="form-group">
                {{ form.first_name|add_class:"form-control"|attr:"placeholder:Имя" }}
            </div>
            <div class="form-group">
                {{ form.last_name|add_class:"form-control"|attr:"placeholder:Фамилия" }}
            </div>
            <div class="form-group">
                {{ form.middle_name|add_class:"form-control"|attr:"placeholder:Отчество" }}
            </div>
            <div class="form-group">
                {{ form.phone|add_class:"form-control"|attr:"placeholder:Телефон" }}
            </div>
            <div class="form-group">
                {{ form.email|add_class:"form-control"|attr:"placeholder:E-mail" }}
            </div>
            <div class="form-group">
                {{ form.city|add_class:"form-control"|attr:"placeholder:Город" }}
            </div>
            <div class="form-group">
                {{ form.idx|add_class:"form-control"|attr:"placeholder:Индекс" }}
            </div>
            <div class="form-group">
                {{ form.address|add_class:"form-control"|attr:"placeholder:Адрес" }}
            </div>
            <div class="form-group">
                <button class="btn btn-dark">Сохранить</button>
            </div>
        </form>
    </div>
{% endblock %}